package ivanauskas.tadas.heartmonitor.Model;

import android.content.Context;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
import android.util.Log;

import java.util.HashSet;

public class MovementDetector implements SensorEventListener {

    private SensorManager sensorMan;
    private Sensor accelerometer;

    private MovementDetector(Context context) {
        try {
            sensorMan = (SensorManager) context.getSystemService(Context.SENSOR_SERVICE);
            accelerometer = sensorMan != null ? sensorMan.getDefaultSensor(Sensor.TYPE_LINEAR_ACCELERATION) : null;
        }catch (NullPointerException e){
            Log.e("MovementDetector",e.getMessage());
        }
    }
    private HashSet<Listener> mListeners = new HashSet<MovementDetector.Listener>();

    public void start() {
        sensorMan.registerListener(this, accelerometer, SensorManager.SENSOR_DELAY_NORMAL);
    }

    public void stop() {
        sensorMan.unregisterListener(this);
    }

    public void addListener(Listener listener) {
        mListeners.add(listener);
    }

    @Override
    public void onSensorChanged(SensorEvent event) {
        if (event.sensor.getType() == Sensor.TYPE_LINEAR_ACCELERATION) {

            float x = event.values[0];
            float y = event.values[1];
            float z = event.values[2];

            float diff = (float) Math.sqrt(x * x + y * y + z * z);
            if (diff > 0.5)
                Log.d("MovementDetector","Device motion detected!!!!");
            for (Listener listener : mListeners) {
                listener.onMotionDetected(event, diff);
            }
        }
    }

    @Override
    public void onAccuracyChanged(Sensor sensor, int accuracy) {
        // autogenerated
    }

    public interface Listener {
        void onMotionDetected(SensorEvent event, float acceleration);
    }
}